appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: m8AfEdekvzFDlJVVL293ieuHCpJCU7eAeLh7kknlrAZgGuevKjdE7Kv4DOJ3N5RcJVofueHo85BoXY4GylzzxyP4acdCb4E8JMms82DzWQprn++Xxzc53VZoHBT/Kf6Y8FynQeXxrrGl6AM7TGh4b1kYtlI1rfciMVC1MS5eYZnvn+icol8fonRG2gqfbDnbfziFCIZHgi5Fbeirtx1venA6fJDNhDbfZyf9/NY4Ifm4Thxe0ySLZOChk1bGQXp95aTDnJLEpIeLkT9sr/O+rVc1eOs/UNiBHw69T82/NK2GnzruBWS8LykDQcXNJaqohmGurCEerF0p8YOrPy/NdNm/MwJu9LFzQsSZzxApjCgdhpQ6ulDTsluuw1rUaanAWOQ2C1Ke6f5mYEzxWbKw/VMVePyzVRWPsyKFLv1Z7WQ/uSf8klJkwHhKidUp8dAh0Ju3ITAn+WXIhbSV0/Wqk4EDU++W6GrS6hoSQfN3xo6dtfWWf7elPNJAZMHzfiafROme1NEweAnwmpsZqx9LyXRP26I7vCAzbwI7HBDbM9MPcM069kvCDWpCcvUFUb2TSsUK1YiDhoOkyYwTWylIsUICjrJ8yDMC80LoIMCwW1JqbBK71THRICsxlTLtwFPjcdI3eKhUcr4HopnwTh/nY0+3m9ReX2Vr6I6ouwueHxM=}
conda_forge_output_validation: true
