travis:
  secure:
    BINSTAR_TOKEN: mpG2fbDfmiYkL5+gl7NqB/bWP+/OnBsjVmJIVJhYtRjgrIWE4AXeNSx57ut8hyA2U5fy8ngQglKeZ3e79DnVAiojZvJ4bKoyvb+waMyN7kYXSwUTNKfhPmYIx/rTpN0CXCYYRuFHkyjc25/o5oBYJgLiqYKk62FWpfR5y5B5Slk/Xb/cQsP+xK8+43Tm8QlYyh7mLFSSEE8ItFL8SJSPXrQXcd1GIkJ3ivl1n82viIUUOidQs8LuuGkEYjsdOh//6oC/PDbh4eZVHSZ/tzSieNVhNGysjYn82h1x5WkJadgS4Q2cPOJttobiT6Jlq7aGxlLtUlg8NhuCLA4w8u9iP4PnkfKvfD/CvKazRM2iCUrwgiJdKYb/Mbt7sn0edVzFWTEaJd1OmWGDA3cF7VvlTf2ScxehAbIyD3rcm39xkkkArviJCa9yHNmrXRVKn33h1S7fc6WTtFPcd8KEfyTFgP+bPwenIZmFfF70LcVH6TB+BPOOFdixERAsRxwWihrahxdapQonq6HZCzsiDeERzj9tQgSdgtDkL224nlKBrB9pGRsNF+4xvO/keWd3kAqkqX6U1duGxNA2cyshp5cw1wqkqOyjvSj3VvXKxkN+sSFNYKHP5DhtM5hYFRB/b2XWuE3SQCPmBAq4EkcPoCh/cxiEXOYGtbvMK4BPSDAt0T8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
