travis:
  secure:
    BINSTAR_TOKEN: YjT9veQe0ezkzRs7nJSn/VJzitJJQMLE9BkWwwp9AC/5bOD60Ab4DU/maguFl9B9Nj/duHC2lV2SkNuuvMybqCwBB3wnp8QovL9CoW4XrpR00ZNmHsBYt5HC+cCJivOzybh+KuwhrE7xVwUVB49sSoyNKgyJHnuHDVRPHvV3GGEkFborKgXtv4tIIH5dH9I/toiB4OjiD4A59C+r37p9/YgK5RI2b6yUCF2nAqmhepS+O43MzKqgwt0HImATZxBLNJmWHY0jC8XrW9ap6zc8ONA+hyX948U6jTSA5gJLRRa8ZZ8jYCrHQhEo2cJhG3lTqvdoMtfmc/ROKwwAJW2CEguJBKJN4vLNy+zmc6xahdv0SJ9T0L2V3UaAWSXbju7GbLjo2GfAwacRbeUCA9XQP9t3KmwjFFyliga5Mn8SAaAdBR8+EHiQtMt+2KC8PdqaeZHRv4b9PKiwLloRKOrJIDgbFOwuCrWedMj12KnZ3P01Ed7I17iUy1w330W3MjAluxZn+XeHdck9dOMsUHSmBn+VDCzqME780gGtBeDMEsXeoQNm88+r5Xu1T6qgY8iqhdVwR1n2iklQxCYu/mR3H96+C1eqwhyokXZtc0iYLMTl2QYC7fv6uBzfWeZGq599FTD8kScNjSb+5m361QoGYqVjv02DbgbLZNhd1XLGJfI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
