travis:
  secure:
    BINSTAR_TOKEN: JKub49sgWHVzCH/o4eRaeUDLuJd5flRlZNpXHL3PLi0jf6ClmJyWI9FS+XOzy4T7LuatkahP6C/YpfJXP/PQIFlT7nWbxIUL2P1ZtppYNkBVHDqZ8Ml1Ys4kSI2LtUPlius4Luos022d21V2gJyTwUx2LWszcq4iqPW8h1kI4gu0a02+sw5X2hm+nYwjiNv7Vcofq5ClyMgvK24cmKwUxMoSJo3gqzkryxGwLtAUnodNRP9ju9+vWuIWoRM5PFwXORUEGFuqMeMWTugdhOBdh2Gg+2beXRazeAsBWoZynaCT8QHFhqqYWemjIv4wE0yJES93sXoL65GxR3ETTiXKeJkxuhQ7a6h0O42iqSl88VchnlRh86vjmkUMLJnEC6yCP4iW9z1skCvsNdH/UfIUgvKV6HYPNmO0icJHPkk0eA6nlz0f2tpKwUR7VNQuStDc+96dCtW/lZKMGHOhBUFiL79Xe2dwBYiOsezK+6AybKn9t95HNN7a5DJH6ZiDpp3mjXJ9pCZ1AhdNuLwNgKGA9f02lF5NI16sUzeU+/DOZ5DnD4ABZyYezEXW6bxLIrAIEs1p3Fqo/7jswFyNi3CFT334+T6a7gZUT+PnyIHaM0IDFBeYecELpM2D5+e+QGkThbBYMNPA3fUR9qRTmaAfQiW/C/3hnO3oP8o39npr/ig=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
